### ISSUE TITLE
Possible missing components or needing update cyfunc.pyx

### ISSUE THREAD

**Issue by thw1021** [brendenpetersen/deep-symbolic-optimization#24]
Dear Petersen,

This import cannot work since `StateChecker`  and `Polynomial` are not defined in `dso.library`. So the `cython_execute` may never be used.
https://github.com/brendenpetersen/deep-symbolic-optimization/blob/8023df67b283b358df2a8798368cf1391ac42c8b/dso/dso/cyfunc.pyx#L10

I noticed that there is no this import in the previous version of `cyfunc.pyx`. Could you have a check, please ?

**Comment by thw1021** [comment]
And by saying ["**_it's not reliable for testing if cython ran_**"](https://github.com/brendenpetersen/deep-symbolic-optimization/blob/8023df67b283b358df2a8798368cf1391ac42c8b/dso/dso/program.py#L450), what do you mean here? I am not familiar with `cython`. I know `cython` is usually used to strengthen the code performance. Could you do a further explanation, please?

**Comment by brendenpetersen** [comment]
Thank you, sorry about this. We've had some issues syncing up the Github repo. I will fix this today.

**Comment by brendenpetersen** [comment]
I just pushed a fix for the bug. Everything should have been running correctly with the bug, it was just not using the Cython version of `execute` (the function that evaluates an expression on some input data--this is also the bottleneck of the code). The Cython version is a bit faster than the pure-Python version.

After pulling the update, you will have to reinstall with `pip install -e ./dso` to recompile the Cython code.

> I know `cython` is usually used to strengthen the code performance

Yes, it's only there for a small performance boost. Since it sometimes has installation issues (as you've seen), we include a pure-Python version as a fallback.

**Comment by thw1021** [comment]
OK, thank you.
