### ISSUE TITLE
Handling invalid or numerically unstable values in sub-expressions for control tasks?

### ISSUE THREAD

**Issue by yfkuang98** [brendenpetersen/deep-symbolic-optimization#66]
Hi, we are following the symbolic control work based on your papers and code. However, we observe that the agent tends to generate expressions that result in invalid or numerically unstable values.

For example, the agent can generate expressions that contain "log(some-sub-expression)" or "1/(some-sub-expression)". These sub-expressions, however, can get negtive (invalid for log function) or extremely small (numerically unstable for / function) values. Note that in control tasks we obtain the certain values of input features only during the control process. Thus, we cannot check whether the values of these sub expressions are valid or not in advance, which tends to cause the program down during the control process due to incorrect numeric values.

I have checked the constraint and prior classes used in the "make_prior" function in prior.py. However, I am not sure which constraint is related to handling this problem. Many thanks!

**Comment by brendenpetersen** [comment]
Hi, sorry for the delay! Great question!

As a design choice, we chose that the `control` task uses _protected_ versions of operators. For example, `protected_log` returns `log(abs(x))`. You can read more about them in `dso/functions.py`.

It is up to the user what to do from there. One option is to not use protected operators, and penalize things like log(negative number) via the reward function. This is what we do by default for the `regression` task. Another option is to just note that the operators are really protected versions, e.g. `protected_log` can be expressed as a piecewise function.

Regarding priors, in general, it is not really possible to avoid things like log of a negative number in a general sense using priors. This is because it relies of the _semantics_ of tokens (and input data), not their syntax. And as you said, for the control task it's even harder because we don't have the data in advance.

That said, it's possible to track some semantic properties, like the domain and range of operators at each node in a traversal, and constrain them to not fall outside your allowed domain and range (e.g. `observation_space` and `action_space` bounds for the `control` task).
